In [7]:
# np.array
import numpy as np

In [14]:
a = np.array([1,2,3])   # vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
# 2D and 3D  #matrix & tensor
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

c  = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [33]:
# dtype
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [34]:
# dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [36]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [32]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
# np.onees and np.zeros
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
# np.onees and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
# np.random
np.random.random((3,4))

array([[0.89403286, 0.77604531, 0.32513575, 0.54327717],
       [0.06821792, 0.00986014, 0.1096042 , 0.46733625],
       [0.26749004, 0.64837258, 0.25966976, 0.26717374]])

In [40]:
# np.linspace(linearly space)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [41]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array attributes

In [43]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
# ndim(dimensional)
a3.ndim


3

In [49]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
# shape
a2.shape

(3, 4)

In [50]:
#size
a3.size

8

In [52]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [54]:
# itemsize
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# itemsize
a1.itemsize


8

In [55]:
# itemsize
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [56]:
# itemsize
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# changing datatype


In [60]:
# astype
a3.dtype

dtype('int64')

In [61]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array operations

In [10]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
# scalar operations

# arithmetic operators
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
# scalar operations

# arithmetic operators
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

# 1. scalar operations



In [11]:
# scalar operations

# arithmetic operators
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [76]:
# relational operators
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
# relational operators
a2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# 2. vector operations

In [9]:
# arithmetic
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# array function

In [14]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 7., 40., 47.],
       [23., 11., 24.],
       [ 4., 54., 63.]])

In [15]:
# max/min/sum/prod

np.max(a1)

np.float64(63.0)

In [16]:
# max/min/sum/prod

np.min(a1)

np.float64(4.0)

In [17]:
# max/min/sum/prod

np.sum(a1)

np.float64(273.0)

In [18]:
# max/min/sum/prod

np.prod(a1)

np.float64(1087381532160.0)

In [22]:
# max/min/sum/prod

np.max(a1,axis=1)

array([47., 24., 63.])

In [23]:
# max/min/sum/prod

np.max(a1,axis=0)

array([23., 54., 63.])

In [24]:
# max/min/sum/prod

np.sum(a1,axis=0)

array([ 34., 105., 134.])

In [25]:
# mean/median/std/var

np.mean(a1,axis=0)

array([11.33333333, 35.        , 44.66666667])

In [27]:
# mean/median/std/var

np.std(a1,axis=0)

array([ 8.33999734, 17.90716802, 16.00694294])

In [29]:
# mean/median/std/var

np.mean

<function mean at 0x0000018E73B9F730>

In [31]:
# trigonometric functions

np.sin(a1)

array([[ 0.6569866 ,  0.74511316,  0.12357312],
       [-0.8462204 , -0.99999021, -0.90557836],
       [-0.7568025 , -0.55878905,  0.1673557 ]])

In [36]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [37]:
# log ans exponents

np.log(a1)

array([[1.94591015, 3.68887945, 3.8501476 ],
       [3.13549422, 2.39789527, 3.17805383],
       [1.38629436, 3.98898405, 4.14313473]])

In [38]:
# log ans exponents

np.exp(a1)

array([[1.09663316e+03, 2.35385267e+17, 2.58131289e+20],
       [9.74480345e+09, 5.98741417e+04, 2.64891221e+10],
       [5.45981500e+01, 2.83075330e+23, 2.29378316e+27]])

In [40]:
# round/floor/ceil

np.random.random((2,3))*100

array([[30.26536941, 60.5479487 , 12.43016201],
       [42.64083542, 75.83239375, 69.65697804]])

In [43]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[51.,  7., 79.],
       [79., 97., 90.]])

In [44]:
# round/floor/ceil

np.floor(np.random.random((2,3))*100)

array([[21., 63., 10.],
       [32., 68., 36.]])

In [45]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[81., 15., 60.],
       [30., 62., 34.]])

# indexing and slicing

In [56]:
a1 = np.arange(10)  # 1D array
a2 = np.arange(12).reshape(3,4)  #2D array
a3 = np.arange(8).reshape(2,2,2)  #3D arry

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a2[2,3]

np.int64(11)

In [61]:
a2[1,0]

np.int64(4)

In [62]:
a3 # tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a3[1,0,1]

np.int64(5)

In [64]:
a3[0,1,0]

np.int64(2)

In [65]:
a3[0,0,0]

np.int64(0)

In [66]:
a3[1,1,0]

np.int64(6)

In [ ]:
# slicing

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a1[2:5]

array([2, 3, 4])

In [69]:
a1[2:5:2] # alternate

array([2, 4])

In [70]:
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a2[0,:]

array([0, 1, 2, 3])

In [72]:
a2[:,2]

array([ 2,  6, 10])

In [75]:
a2[1:,1:3] 

array([[ 5,  6],
       [ 9, 10]])

In [76]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [85]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [105]:
a2[1,::3]

array([4, 7])

In [115]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [118]:
a3 =  np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [120]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
a3[1,:,1]

array([10, 13, 16])

In [122]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [132]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [136]:
a1
for i in a1: 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [137]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [138]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [140]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

In [142]:
# Transpose

np.transpose(a2)

# or both one things

a2.T



array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [145]:
# ravel

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking 

In [160]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [151]:
np.stack((a4,a5))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [154]:
# verticel stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [159]:
# horizontal spillting

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [161]:
#vertical splliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [165]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]